[package]
authors = ["Ramla Ijaz <ijazramla@gmail.com>"]
name = "prusti_external_spec"
description = "Specifications for types in the core library."
version = "0.1.0"
edition = "2021"

[dependencies]
prusti-contracts = "0.2"

[lib]
crate-type = ["rlib"]