check_overflows = false
use_new_encoder = false
skip_unsupported_features = true # removing all cfg and enabling this flag is giving the "chaining pure functions is not fully supported" prusti error, so will keep some cfg gates for now
# opt_in_verification = true # this flag is causing strange behavior with the Partial Ord external spec so will stick with cfg for now.
# allow_unreachable_unsupported_code = true