check_overflows = false
use_new_encoder = false
enable_type_invariants = true
skip_unsupported_features = true # This doesn't work for [derive(Debug)] here though it does in other crates
no_verify_deps = true
# opt_in_verification = true
# allow_unreachable_unsupported_code = true

